name: Main CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "*" # Use the LTS Node.js version
          cache: "npm"
          cache-dependency-path: './package-lock.json'
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: npm run test
      - run: npm run test:cucumber